### ISSUE TITLE
Show compiled javascript

### ISSUE THREAD

**Issue by joeldenning** [huytd/coffee-now#3]
I appreciate your work on this - coffeescript isn't as popular anymore but I still have been learning it recently.

I'd love to see the compiled javascript output, as a way to help me learn coffeescript. I've searched a bit for other websites that would do this, but haven't found any.

**Comment by huytd** [comment]
Hey, thanks for the suggestion, I just pushed an update for this. Now the UI should have 2 editors side by side, the right one is readonly and will show the compiled JavaScript whenever you run, there's also a Compile button to compile the code without running it.

**Comment by internettrans** [comment]
Wow, thanks. Just tried it out and it works great!
